fix(station): corrected SDk to SDK
memphisdev/memphis-broker pull request #255
Opened 2022-08-08 21:27 UTC by bsmirks

This is a fix for #252 in which I found instances of the word `SDk` and replaced with `SDK`. Please let me know if anything was missed in the contribution workflow. Thanks!

2022-08-09 08:14 UTC, OrMemphis requested changes
It's better if this message was a constant for the whole package, maybe call it invalidHeaderErrMessage. you can place it anywhere you see fit

2022-08-09 08:18 UTC, OrMemphis commented
Hey @bsmirks,  all good with the contribution workflow!
I had a minor [suggestion](https://github.com/memphisdev/memphis-broker/pull/255#pullrequestreview-1066299364) before merging, thanks a lot for your contribution.

2022-08-09 21:27 UTC, bsmirks commented
Sounds good, I will play with implementing this and update the PR accordingly.

2022-08-09 21:43 UTC, bsmirks commented
I've updated `poison_messages.go`  before the first function is defined to contain a constant which stores the error message, then called it where needed.

2022-08-10 12:12 UTC, OrMemphis reviewed
Nice, although my naming may have confused a little, I think we can include that "Error while getting notified..." in the constant if it's not being used in parts anywhere else.
that said, probably the name should suggest that it only comes from poison messages, like `invalidPosionHeaderErrMessage`

2022-08-10 12:12 UTC, OrMemphis commented on handlers/poison_messages.go
> +const invalidHeaderErrMessage string = "Missing mandatory message headers, please upgrade the SDK version you are using"
```suggestion
const invalidPoisonHeaderErrMessage string = "Error while getting notified about a poison message: Missing mandatory message headers, please upgrade the SDK version you are using"
```

2022-08-10 12:12 UTC, OrMemphis commented on handlers/poison_messages.go
> +		logger.Error("Error while getting notified about a poison message: " + invalidHeaderErrMessage)
```suggestion
		logger.Error(invalidPoisonHeaderErrMessage)
```

2022-08-10 12:12 UTC, OrMemphis commented on handlers/stations.go
> +		c.AbortWithStatusJSON(configuration.SHOWABLE_ERROR_STATUS_CODE, gin.H{"message": "Error while getting notified about a poison message: " + invalidHeaderErrMessage})
```suggestion
		logger.Error(invalidPoisonHeaderErrMessage)
		c.AbortWithStatusJSON(configuration.SHOWABLE_ERROR_STATUS_CODE, gin.H{"message": invalidPoisonHeaderErrMessage})
```

2022-08-10 12:26 UTC, OrMemphis commented
@bsmirks thanks! consider my suggestions;
if these messages are being used in parts' tell me and I'll approve and merge. 
else, you can commit my suggestions and I'll approve.

btw you are more than welcome to our [Discord](https://discord.gg/Ua9r56Gb) server, I'm there if you have any question

2022-08-10 14:12 UTC, bsmirks commented
I have made a change to the name of the constant as suggested as I think that making the constant more descriptive is worthwhile in the long run for readability's sake. 

However, I think that the bit about "Error while getting notified about..." should stay as is since it is being used in parts elsewhere like [here](https://github.com/bsmirks/memphis-broker/blob/bsmirks-sdk-typo/handlers/poison_messages.go#L103) which is where I got the convention for leaving it there and appending the constant afterwards. Let me know what you think!

Joined the Discord :)

2022-08-10 14:45 UTC, OrMemphis approved these changes

2022-08-10 14:46 UTC, merged